### ISSUE TITLE
Gstreamer no audio output

### ISSUE THREAD

**Issue by redargon** [ardera/flutter-pi#233]
I read in #218 that you had not yet implemented audio for gstreamer. Is this still the case? I have tried a few different video formats, but do not get any audio output.

**Comment by ardera** [comment]
Yep that's still the case, working on it

**Comment by redargon** [comment]
Great, thanks for the fast feedback.

**Comment by ioridev** [comment]
When will this be worked on?

**Comment by Binozo** [comment]
any updates?

**Comment by Binozo** [comment]
@ardera 
Sorry but I couldn't get it to work.

Here are my logs:

```
[flutter-pi] WARNING: display didn't provide valid physical dimensions. The device-pixel ratio will default to 1.0, which may not be the fitting device-pixel ratio for your display.

(flutter-pi:627): GLib-GObject-WARNING **: 17:49:37.994: g_object_set_is_valid_property: object class 'GstPlayBin' has no property named 'force-sw-decoders'
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
[gstreamer video_player] Could not query buffering state. (gst_element_query)
AL lib: (EE) ALCplaybackAlsa_reset: snd_pcm_hw_params(self->pcmHandle, hp) failed: File descriptor in bad state
[gstreamer video player] gstreamer error: code: 1, domain: gst-resource-error-quark, msg: Unable to prepare device. (debug info: ../ext/openal/gstopenalsink.c(858): gst_openal_sink_prepare (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstOpenALSink:openalsink0:
ALC error: Invalid Device)
[gstreamer video player] gstreamer error: code: 11, domain: gst-stream-error-quark, msg: The stream is in the wrong format. (debug info: ../gst-libs/gst/audio/gstaudiobasesink.c(1191): gst_audio_base_sink_preroll (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstOpenALSink:openalsink0:
sink not negotiated.)
[gstreamer video player] gstreamer error: code: 1, domain: gst-stream-error-quark, msg: Internal data stream error. (debug info: ../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
streaming stopped, reason not-negotiated (-4))
[compositor] GPU does not supported the desired HW plane order.
  Some UI layers may be invisible.

```

**Comment by ardera** [comment]
Are you running raspbian buster? buster has pretty old gstreamer 1.14, bullseye has 1.18. Gstreamer has seen a lot of improvements between those versions, I'm pretty sure upgrading to bullseye will fix it.

Or, if you rely on buster, try building & installing latest gstreamer yourself.

**Comment by ardera** [comment]
@Binozo can you try installing `gstreamer1.0-alsa` if it's not installed already?

**Comment by Binozo** [comment]
Now it started working :)

Thank you!

**Comment by ardera** [comment]
Np, I'll add that to the dependencies section then.

**Comment by tobiasht** [comment]
Has anyone managed go get audio working? I am using the [`audioplayers`](https://pub.dev/packages/audioplayers) package. Audio works fine in Mac and Web.

```
[audioplayers plugin] Call missing mandatory parameter player_id.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(illegalargument, Expected `arg['player_id'] to be a string., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:131:5)
<asynchronous suspension>
#3      GameNotifier.operatorNextStep (package:save_the_penguins/app/features/game/providers/game_providers.dart:93:7)
<asynchronous suspension>
```

**Comment by tobiasht** [comment]
@ardera have you gotten audio to work?

**Comment by innomatica** [comment]
I'm having exactly the same PlatformException as @ardera. Flutter version is 3.7.7.

According to 'audioplayers', this playerId is [set to uuid.v4 by default](https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers/lib/src/audioplayer.dart#L99). 

This doesn't seem to be understood by the method channel when [the audio source is set.](https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers/lib/src/audioplayer.dart#L228) And the PlatformException was thrown [by this](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/message_codecs.dart#L168) 

I tried to set the playerId manually with a random string, but to no avail.

**Comment by edlman** [comment]
Hello, I installed `flutter-pi` and run an app with VideoPlayer (using pkg flutterpi_gstreamer_video_player). It plays video, but there is no audio. When I play the same video file on the same RPi in different player (VLC, QtMediaPlayer, Chrome browser), it works. So the audio settings (alsa or whatever) is ok.
I'm confused and don't know how to fix it. 
My RPi is running RasbperryPi OS based on Debian 11 (Bullseye), latest flutter pi (downloaded and built yesterday), Flutter app is built using latest Flutter 3.27.2

**Comment by edlman** [comment]
After some time I returned back to flutter pi to see if the audio issue is resolved. Nope, it's not. It's still the same. I upgraded Flutter to 3.38.9 (using 3.41.1 didn't work, there are some issues), upgraded flutter packages (flutterpi_gstreamer_video_player: ^0.2.0, video_player: ^2.11.0, flutterpi_tool: ^0.10.1), upgraded Flutter pi on the RPi. No audio from the app.
The video (mp4) and audio (mp3, wav) play normally from other apps (vlc, gst123, ...) without any special params to ALSA, using the system default device HDMI1 (set in raspi-config).
Is there any solution?

**Comment by ardera** [comment]
@edlman you can try the devel branch: https://github.com/ardera/flutter-pi/tree/devel
with the feat/video-player-audio branch from here: https://github.com/ardera/flutter_packages/tree/feat/video-player-audio
