### ISSUE TITLE
 the 'build/flutter_assets' was empty

### ISSUE THREAD

**Issue by kero990** [ardera/flutter-pi#359]
I attempted to compile this project in an arm64 debian10 (Docker) environment, and did not see any errors during the process, but the 'build/flutter_assets' was empty and no files were generated. Is this # 1-13 actually an error message?May I ask what the situation is.

```
root@f8c3c9b8554e:~/pilipala# flutterpi_tool build --arch=arm64 --release
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Unhandled exception:
Unsupported operation: Unsupported host platform: HostPlatform.linux_arm64
#0      FlutterpiArtifactPaths.getHostDirName (package:flutterpi_tool/src/build_bundle.dart:171:12)
#1      FlutterpiArtifactPaths.getEngineSource (package:flutterpi_tool/src/build_bundle.dart:227:25)
#2      CopyFlutterpiEngine.inputs (package:flutterpi_tool/src/build_bundle.dart:575:24)
#3      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:196:34)
#4      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:149:39)
#5      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:156:58)
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:609:30)
#7      buildFlutterpiBundle (package:flutterpi_tool/src/build_bundle.dart:892:36)
#8      BuildCommand.run.<anonymous closure> (package:flutterpi_tool/src/build_bundle.dart:1179:17)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     BuildCommand.run (package:flutterpi_tool/src/build_bundle.dart:1166:5)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     main (package:flutterpi_tool/src/build_bundle.dart:1269:16)
<asynchronous suspension>
#13     main (file:///root/.pub-cache/hosted/pub.flutter-io.cn/flutterpi_tool-0.1.2/bin/flutterpi_tool.dart:4:3)
<asynchronous suspension>


root@f8c3c9b8554e:~/pilipala# flutter-pi --release build/flutter_assets/
filesystem_layout.c: icudtl file not found!
root@f8c3c9b8554e:~/pilipala# ls build/flutter_assets/ -a
.  ..
```

**Comment by ardera** [comment]
Yep, that's an error message because linux arm64 is not supported right now as a host platform, unfortunately

You need to run it on a x64 machine
