### ISSUE TITLE
Touch input not working

### ISSUE THREAD

**Issue by MihirGrand** [ardera/flutter-pi#390]
Hello again!

I am able to see my app well on the display, its a 3.5" touch display

I am also able to get some output on touch through libinput debug, but no onpressed event firing on touching buttons

I'm assuming I have a similar problem to those mentioned in some previous issues where the calibration was off

I tried building your calibrator at https://github.com/ardera/flutter_libinput_calibrator using flutter-pi with the usual steps but I get the following error -

../.pub-cache/hosted/pub.dev/google_fonts-3.0.1/lib/src/google_fonts_base.dart:14:1: Error: 'AssetManifest' is imported
from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
import 'asset_manifest.dart';
^^^^^^^^^^^^^
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer
named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' doesn't have
the named parameter 'exclusive' of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method
'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method
'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../.pub-cache/hosted/pub.dev/google_fonts-3.0.1/lib/src/google_fonts_base.dart:32:31: Error: 'AssetManifest' is imported
from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
AssetManifest assetManifest = AssetManifest();
                              ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:274:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#9      buildFlutterpiBundle (package:flutterpi_tool/src/build_bundle.dart:375:20)
<asynchronous suspension>
#10     BuildCommand.run.<anonymous closure> (package:flutterpi_tool/src/build_bundle.dart:668:11)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     BuildCommand.run (package:flutterpi_tool/src/build_bundle.dart:632:5)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     main (package:flutterpi_tool/src/build_bundle.dart:777:5)
<asynchronous suspension>
#15     main (file:///home/mihir/.pub-cache/hosted/pub.dev/flutterpi_tool-0.3.0/bin/flutterpi_tool.dart:4:3)
<asynchronous suspension>

Building Flutter-Pi bundle...
Failed to build bundle.

How do I proceed from here? If not to use this tool, how do I manually debug and calibrate the display?

**Comment by MihirGrand** [comment]
More context -

When I first ran my app using flutter-pi on my 3.5" touchscreen, I got some error related to DRM. I headed over to /boot/config.txt and uncommented dtoverlay=vc4-kms-v3d and rebooted.

After the reboot, I tried running my app again. This time, I got no errors, but the terminal was still visible and my app didn't show up. 

According to an old issue I found, I changed dtoverlay to dtoverlay=vc4-**f**kms-v3d, rebooted. This time, the terminal wasn't visible at all times, it showed up only when it updated. Hence I could see text when I ran some command, and the constantly blinking cursor. But I tried running my app, and it showed up perfectly!

Touch inputs didnt respond though. Since your calibration tool wasn't building, I decided to use ts_calibrate. Switched the dtoverlay again and rebooted so I could see the terminal and the ts_calibrate window, and calibrated the display. I was able to draw perfectly in ts_test. I figured my display was calibrated now, so I switched the dtoverlay again and ran my app after a reboot. But still no response to touch input! I also tried connecting a mouse and clicking the button and well, it works that way. 

What could be going wrong?

**Comment by MihirGrand** [comment]
So I copied the code from your libinput calibrator, pasted it in a new project, and it built successfully without google fonts. I ran it on my raspberrypi but there's one issue, the app goes out of bounds of the display horizontally, it extends beyond so some part is cut and I can't access the targets on the right. How do I fix the resolution issue? I already set the framebuffer width to 480 and framebuffer height to 320 in /boot/config.txt
